Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="171" judge-id="119" status="SE" scoring="ACM" run-tests="1" contest-id="3203" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="1" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>dc53d08c-482f-4e0e-91ad-ad0371029206</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="SE" time="287" real-time="304" max-memory-used="18698240" >
  <program-stats-str>{ utime=274, stime=13, ptime=287, rtime=304, maxvsz=18698240, maxrss=19103744, nvcsw=1, nivcsw=45 }</program-stats-str>
      <input size="2">2
</input>
      <output size="0"></output>
      <stderr size="277">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000171&quot;, line 6, in &lt;module&gt;
    while m &lt; x:
NameError: name 'x' is not defined
</stderr>
    </test>
  </tests>
</testing-report>
