Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="117" judge-id="33" status="SE" scoring="ACM" run-tests="1" contest-id="3205" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="1" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>7169abb5-b80a-48f2-9565-df85136681bc</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="SE" time="290" real-time="318" max-memory-used="32251904" >
  <program-stats-str>{ utime=215, stime=75, ptime=290, rtime=318, maxvsz=32251904, maxrss=19439616, nvcsw=1, nivcsw=41 }</program-stats-str>
      <input size="10">1 2 3 2 1
</input>
      <output size="0"></output>
      <stderr size="302">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000117&quot;, line 8, in &lt;module&gt;
    if a[i] &gt;= range(a(i),len(a)) :
TypeError: 'list' object is not callable
</stderr>
    </test>
  </tests>
</testing-report>
