Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="41" judge-id="1" status="SE" scoring="ACM" run-tests="1" contest-id="3104" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="1" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>8a5926fd-9114-4bd1-b6b2-d72c89dd255b</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="SE" time="285" real-time="300" max-memory-used="18698240" >
  <program-stats-str>{ utime=248, stime=37, ptime=285, rtime=300, maxvsz=18698240, maxrss=19152896, nvcsw=1, nivcsw=45 }</program-stats-str>
      <input size="2">2
</input>
      <output size="0"></output>
      <stderr size="285">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000041&quot;, line 16, in &lt;module&gt;
    print (fi_sum)
NameError: name 'fi_sum' is not defined
</stderr>
    </test>
  </tests>
</testing-report>
