Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="147" judge-id="5" status="SE" scoring="ACM" run-tests="3" contest-id="3104" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="3" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>320da9ae-6f55-4cb4-9d30-f1fa6ae8a5be</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="OK" time="26" real-time="28" max-memory-used="307200"  checker-comment="OK" >
  <program-stats-str>{ utime=11, stime=15, ptime=26, rtime=28, maxvsz=307200, maxrss=6213632, nvcsw=1, nivcsw=7 }</program-stats-str>
  <checker-stats-str>{ utime=0, stime=0, ptime=0, rtime=2, maxvsz=307200, maxrss=2285568, nvcsw=1, nivcsw=1 }</checker-stats-str>
      <input size="2">4
</input>
      <output size="2">7
</output>
      <correct size="2">7
</correct>
      <stderr size="0"></stderr>
      <checker size="3">OK
</checker>
    </test>
    <test num="2" status="OK" time="27" real-time="29" max-memory-used="307200"  checker-comment="OK" >
  <program-stats-str>{ utime=24, stime=3, ptime=27, rtime=29, maxvsz=307200, maxrss=6299648, nvcsw=1, nivcsw=4 }</program-stats-str>
  <checker-stats-str>{ utime=0, stime=0, ptime=0, rtime=1, maxvsz=307200, maxrss=2285568, nvcsw=1, nivcsw=1 }</checker-stats-str>
      <input size="2">5
</input>
      <output size="3">13
</output>
      <correct size="3">13
</correct>
      <stderr size="0"></stderr>
      <checker size="3">OK
</checker>
    </test>
    <test num="3" status="SE" time="287" real-time="309" max-memory-used="18698240" >
  <program-stats-str>{ utime=246, stime=41, ptime=287, rtime=309, maxvsz=18698240, maxrss=19243008, nvcsw=1, nivcsw=42 }</program-stats-str>
      <input size="2">1
</input>
      <output size="0"></output>
      <stderr size="287">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000147&quot;, line 7, in &lt;module&gt;
    lst[1] = 2
IndexError: list assignment index out of range
</stderr>
    </test>
  </tests>
</testing-report>
