Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="148" judge-id="6" status="SE" scoring="ACM" run-tests="3" contest-id="3104" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="3" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>6780528b-8b32-4eab-b7d4-c5a15943bf97</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="OK" time="26" real-time="29" max-memory-used="307200"  checker-comment="OK" >
  <program-stats-str>{ utime=20, stime=6, ptime=26, rtime=29, maxvsz=307200, maxrss=6258688, nvcsw=1, nivcsw=7 }</program-stats-str>
  <checker-stats-str>{ utime=0, stime=0, ptime=0, rtime=1, maxvsz=307200, maxrss=2285568, nvcsw=1, nivcsw=1 }</checker-stats-str>
      <input size="2">4
</input>
      <output size="2">7
</output>
      <correct size="2">7
</correct>
      <stderr size="0"></stderr>
      <checker size="3">OK
</checker>
    </test>
    <test num="2" status="OK" time="26" real-time="29" max-memory-used="307200"  checker-comment="OK" >
  <program-stats-str>{ utime=23, stime=3, ptime=26, rtime=29, maxvsz=307200, maxrss=6205440, nvcsw=1, nivcsw=4 }</program-stats-str>
  <checker-stats-str>{ utime=0, stime=0, ptime=0, rtime=2, maxvsz=307200, maxrss=2285568, nvcsw=1, nivcsw=1 }</checker-stats-str>
      <input size="2">5
</input>
      <output size="3">13
</output>
      <correct size="3">13
</correct>
      <stderr size="0"></stderr>
      <checker size="3">OK
</checker>
    </test>
    <test num="3" status="SE" time="287" real-time="484" max-memory-used="29560832" >
  <program-stats-str>{ utime=243, stime=44, ptime=287, rtime=484, maxvsz=29560832, maxrss=19120128, nvcsw=1, nivcsw=45 }</program-stats-str>
      <input size="2">1
</input>
      <output size="0"></output>
      <stderr size="287">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000148&quot;, line 7, in &lt;module&gt;
    lst[2] = 2
IndexError: list assignment index out of range
</stderr>
    </test>
  </tests>
</testing-report>
